"use client"

import { useState } from "react"
import { Brain, Gauge, Loader2, RefreshCw, Sparkles, TrendingUp } from "lucide-react"
import { useEventAiInsight } from "@/lib/queries/events"

// Organizer/admin-only: real AI insight for one managed event, generated by
// the LLM provider server-side (Gemini → Groq) with a deterministic
// fallback, plus the attendance forecast (AI regressor with a velocity
// heuristic fallback). A refresh button re-runs the full pipeline.
export function EventAiInsights({ eventId }: { eventId: string }) {
  const [refreshing, setRefreshing] = useState(false)
  const { data, isLoading, isError, refetch } = useEventAiInsight(eventId)

  const refresh = async () => {
    setRefreshing(true)
    await refetch()
    setRefreshing(false)
  }

  return (
    <div className="rounded-2xl border border-primary/20 bg-primary/[0.04] p-6">
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <span className="bg-brand-gradient flex size-9 items-center justify-center rounded-xl text-white">
            <Brain className="size-5" />
          </span>
          <div>
            <h2 className="font-display text-base font-bold text-ink">AI Insights</h2>
            <p className="text-xs text-muted-foreground">
              Generated from your live event data
            </p>
          </div>
        </div>
        {data && !isLoading && (
          <button
            onClick={refresh}
            disabled={refreshing}
            className="flex items-center gap-1.5 rounded-lg border border-border bg-card px-3 py-1.5 text-xs font-medium text-ink transition-colors hover:bg-muted disabled:opacity-60"
          >
            {refreshing ? <Loader2 className="size-3.5 animate-spin" /> : <RefreshCw className="size-3.5" />}
            Regenerate
          </button>
        )}
      </div>

      {isLoading || refreshing ? (
        <div className="mt-5 flex items-center justify-center gap-2 rounded-xl border border-border bg-card py-8 text-sm text-muted-foreground">
          <Loader2 className="size-4 animate-spin text-primary" /> Asking the AI model…
        </div>
      ) : isError || !data ? (
        <p className="mt-5 rounded-xl border border-dashed border-border bg-card px-4 py-6 text-center text-sm text-muted-foreground">
          Couldn't generate an insight right now. Make sure you're the organizer or an admin of this
          event's organization.
        </p>
      ) : (
        <div className="mt-5 grid gap-4 lg:grid-cols-2">
          <div className="rounded-xl border border-border bg-card p-4">
            <div className="flex items-center justify-between gap-2">
              <span className="inline-flex items-center gap-1 text-xs font-semibold text-primary">
                <Sparkles className="size-3.5" /> Demand analysis
              </span>
              <span
                className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${
                  data.source === "ai" ? "bg-primary/10 text-primary" : "bg-amber-500/15 text-amber-600"
                }`}
              >
                {data.source === "ai" ? "AI generated" : "Smart estimate"}
              </span>
            </div>
            <p className="mt-2.5 text-sm leading-relaxed text-ink">{data.insight}</p>
          </div>

          <div className="rounded-xl border border-border bg-card p-4">
            <span className="inline-flex items-center gap-1 text-xs font-semibold text-secondary">
              <TrendingUp className="size-3.5" /> Attendance forecast
            </span>
            <div className="mt-3 grid grid-cols-3 gap-3 text-center">
              <div>
                <p className="font-display text-xl font-bold text-ink">{data.forecast.registered}</p>
                <p className="text-[10px] uppercase tracking-wide text-muted-foreground">Now</p>
              </div>
              <div>
                <p className="font-display text-xl font-bold text-secondary">{data.forecast.predicted}</p>
                <p className="text-[10px] uppercase tracking-wide text-muted-foreground">Projected</p>
              </div>
              <div>
                <p className="font-display text-xl font-bold text-muted-foreground">{data.forecast.capacity}</p>
                <p className="text-[10px] uppercase tracking-wide text-muted-foreground">Capacity</p>
              </div>
            </div>
            <div className="mt-3 flex items-center gap-1.5 text-xs text-muted-foreground">
              <Gauge className="size-3.5" />
              {data.forecast.capacity > 0
                ? `${Math.round((data.forecast.predicted / data.forecast.capacity) * 100)}% of capacity expected`
                : "Unlimited capacity — no occupancy constraint"}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}